---
title: "Moje Poznámky"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warnings=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
```

# Statistika:
```{r}
df <- read.csv("StudentsPerformance.csv")
avg <- mean(df$math.score)

# v <- 1:length(df$math.score)
# for(i in 1:length(df$math.score)){
#   v[i] <- abs(mean(sample(df$math.score,i))-avg)
# }
# plot(1:length(df$math.score),v,type = "l",xlab = "počet vzorků",ylab="střední hodnota")

i <- 1:nrow(df)
avg <- mean(df$math.score)
y <- sapply(i,function(n) abs(mean(dplyr::slice_sample(df,n=n)$math.score)-avg))
plot(i,y, type = "l",xlab = "počet vzorků",ylab="střední hodnota")
```

# Korelace a regrese:
```{r}
df <- read.csv("StudentsPerformance.csv")
model1 <- lm(df$reading.score ~ df$math.score)
model2 <- lm(df$writing.score ~ df$math.score)
par(mfrow = c(1, 2))

plot(df$math.score, df$reading.score, xlab="math score", ylab ="reading score",
     main = paste("Pearson=",round(cor(df$reading.score,df$math.score),5),
     "\nSpearman=",round(cor(df$reading.score,df$math.score,method = "spearman"),5)))
abline(model1, col="blue")
plot(df$math.score, df$writing.score, xlab="math score", ylab ="writing score",
     main = paste("Pearson=",round(cor(df$writing.score,df$math.score),5),
     "\nSpearman=",round(cor(df$writing.score,df$math.score,method = "spearman"),5)))
```


abline(model2, col="blue")
